import enum


class RoleName(str, enum.Enum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class GeneratorType(str, enum.Enum):
    MAIN = "MAIN"
    BACKUP = "BACKUP"


class FuelType(str, enum.Enum):
    A92 = "A92"
    A95 = "A95"
    DIESEL = "DIESEL"
    GAS = "GAS"


class EventType(str, enum.Enum):
    GENERATOR_CREATED = "GENERATOR_CREATED"
    GENERATOR_SETTINGS_UPDATED = "GENERATOR_SETTINGS_UPDATED"
    GENERATOR_DEACTIVATED = "GENERATOR_DEACTIVATED"
    MAINTENANCE_PERFORMED = "MAINTENANCE_PERFORMED"
    SHIFT_STARTED = "SHIFT_STARTED"
    SHIFT_STOPPED = "SHIFT_STOPPED"
    SYSTEM_SETTINGS_UPDATED = "SYSTEM_SETTINGS_UPDATED"
    FUEL_DELIVERED = "FUEL_DELIVERED"
    FUEL_REFILLED = "FUEL_REFILLED"
    FUEL_STOCK_UPDATED = "FUEL_STOCK_UPDATED"
    OIL_STOCK_UPDATED = "OIL_STOCK_UPDATED"
    ADJUSTMENT_CREATED = "ADJUSTMENT_CREATED"


class AdjustmentType(str, enum.Enum):
    MOTOHOURS_ADJUST = "MOTOHOURS_ADJUST"
    TO_DATE_ADJUST = "TO_DATE_ADJUST"
    FUEL_STOCK_ADJUST = "FUEL_STOCK_ADJUST"
    FUEL_TANK_ADJUST = "FUEL_TANK_ADJUST"
    OIL_STOCK_ADJUST = "OIL_STOCK_ADJUST"
    INITIAL_DATA = "INITIAL_DATA"


class ShiftStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
